CAN_BAUD_250K = b"250"
CANUSB_ACCEPTANCE_CODE_ALL = 0x0
CANUSB_ACCEPTANCE_MASK_ALL = 0xFFFFFFFF
FLUSH_WAIT = 0x0
FLUSH_DONTWAIT = 0x1
CANUSB_FLAG_TIMESTAMP = 0x1

CANSTATUS_NO_ERROR = 0x0
CANSTATUS_RECEIVE_FIFO_FULL = 0x1
CANSTATUS_TRANSMIT_FIFO_FULL = 0x2
CANSTATUS_ERROR_WARNING = 0x4
CANSTATUS_DATA_OVERRUN = 0x8
CANSTATUS_ERROR_PASSIVE = 0x20
CANSTATUS_ARBITRATION_LOST = 0x40
CANSTATUS_BUS_ERROR = 0x80
